### ISSUE TITLE
Make it compatible with Input-Mod

### ISSUE THREAD

**Issue by cheatfreak47** [PiKeyAr/sadx-keyboard-remap#1]
As the issue says, it's a known issue that it is incompatible with the SADX Input Mod, and it'd be nice if, in some way, this thing could detect and release input to and from real Gamepads via Input mod, depending on the the last used input type.

I.E.
Keyboard Remap active when the last input used is Keyboard
Input Mod active when the the last input used is Gamepad

I haven't looked at your source code yet but there _has_ to be some way to accomplish this, surely.

**Comment by PiKeyAr** [comment]
Nope, not interested.
